---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  tags:
  - docker
  tasks:
    - name: remove docker overrides, specifically to deal with conflicting options from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent
      when: docker_install | default('yes')

- hosts: "{{ hostlist | default('all') }}"
  become: true
  become_method: sudo
  tags:
  - docker
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: geerlingguy.pip
      when: docker_install | default('yes')
    - role: geerlingguy.docker
      when: docker_install | default('yes')
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
